spring.application.name=batch

# \uD55C\uAD6D\uD22C\uC790\uC99D\uAD8C Open API
external.kis.base-url=${KIS_BASE_URL:https://openapivts.koreainvestment.com:29443}
external.kis.app-key=${KIS_APP_KEY:}
external.kis.app-secret=${KIS_APP_SECRET:}
external.kis.timeout=5s
